In [98]:
import pandas as pd
import numpy as np

In [99]:
data = pd.read_csv('diabetes_prediction_dataset.csv')
data.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [100]:
print(data.shape)
print(data.isnull().sum())

(100000, 9)
gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [101]:
count_0, count_1 =data['diabetes'].value_counts()

In [102]:
data_0 = data.loc[data['diabetes'] == 0]
data_1 = data.loc[data['diabetes'] ==1]
print(data_0.head())
print(data_1.head())

   gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19
1  Female  54.0             0              0         No Info  27.32
2    Male  28.0             0              0           never  27.32
3  Female  36.0             0              0         current  23.45
4    Male  76.0             1              1         current  20.14

   HbA1c_level  blood_glucose_level  diabetes
0          6.6                  140         0
1          6.6                   80         0
2          5.7                  158         0
3          5.0                  155         0
4          4.8                  155         0
    gender   age  hypertension  heart_disease smoking_history    bmi  \
6   Female  44.0             0              0           never  19.31
26    Male  67.0             0              1     not current  27.32
38    Male  50.0             1              0         current  27.32
40    Male  73.0             0              0          former  25.91
53  Female  53.0             0              0          former  27.32

    HbA1c_level  blood_glucose_level  diabetes
6           6.5                  200         1
26          6.5                  200         1
38          5.7                  260         1
40          9.0                  160         1
53          7.0                  159         1

In [103]:
#OVER SAMPLING DATA

data_1_over = data_1.sample(count_0, replace=True)

In [104]:
data_1_over.head(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
86137,Male,66.0,0,0,former,41.55,6.8,159,1
81226,Male,76.0,0,1,current,34.74,8.8,300,1
75694,Female,74.0,0,0,never,27.32,8.8,240,1
4615,Female,69.0,0,1,current,20.25,6.2,126,1
45002,Male,66.0,0,1,ever,40.84,8.2,160,1
39910,Female,39.0,0,0,never,35.97,5.7,145,1
13118,Female,80.0,0,1,No Info,30.62,6.6,220,1
7987,Male,6.0,0,0,never,15.69,6.1,220,1
39549,Female,80.0,0,0,never,25.02,9.0,145,1
85977,Male,79.0,1,1,No Info,30.50,6.8,140,1

In [105]:
df = pd.concat([data_0, data_1_over], axis=0,ignore_index=True)
df.shape

(183000, 9)

In [106]:
df.tail(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
182990,Female,51.0,0,0,No Info,39.86,6.5,200,1
182991,Male,74.0,1,0,never,37.36,7.5,126,1
182992,Male,51.0,0,0,current,26.95,6.6,280,1
182993,Male,34.0,0,0,former,24.37,6.2,126,1
182994,Male,51.0,0,0,ever,25.00,8.8,130,1
182995,Female,73.0,1,1,former,33.50,6.2,280,1
182996,Male,50.0,0,0,never,48.01,6.1,126,1
182997,Male,45.0,0,0,No Info,33.44,6.0,220,1
182998,Female,58.0,0,0,former,30.54,6.1,240,1
182999,Female,56.0,0,0,never,67.27,5.7,280,1

In [107]:
df.diabetes.value_counts()

diabetes
0    91500
1    91500
Name: count, dtype: int64

In [108]:
print(df['smoking_history'].value_counts())
print(df['gender'].value_counts())

smoking_history
never          67773
No Info        49979
former         25022
current        18469
not current    13156
ever            8601
Name: count, dtype: int64
gender
Female    102047
Male       80935
Other         18
Name: count, dtype: int64

In [109]:
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder

label_gender = LabelEncoder()
ohe_smoking = OneHotEncoder()
standard_scaler = StandardScaler()

In [110]:
df['gender'] = np.array(label_gender.fit_transform(df['gender']))
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,never,25.19,6.6,140,0
1,0,54.0,0,0,No Info,27.32,6.6,80,0
2,1,28.0,0,0,never,27.32,5.7,158,0
3,0,36.0,0,0,current,23.45,5.0,155,0
4,1,76.0,1,1,current,20.14,4.8,155,0

In [111]:
smoke_encoder = ohe_smoking.fit_transform(df[['smoking_history']])
print(ohe_smoking.get_feature_names_out(['smoking_history']))

['smoking_history_No Info' 'smoking_history_current'
 'smoking_history_ever' 'smoking_history_former' 'smoking_history_never'
 'smoking_history_not current']

In [112]:
smoke_encoder.toarray()

array([[0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [113]:
smoking_df = pd.DataFrame(smoke_encoder.toarray(), columns=ohe_smoking.get_feature_names_out(['smoking_history']))
smoking_df.head()

,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0

In [114]:
smoking_df = smoking_df.reindex(index= range(len(df)))
df=df.reindex(index= range(len(df)))

In [115]:
df = pd.concat([df.drop('smoking_history', axis =1),smoking_df], axis=1)

In [116]:
df['diabetes'].value_counts()

diabetes
0    91500
1    91500
Name: count, dtype: int64

In [117]:
x = df.drop('diabetes', axis=1)
y = df['diabetes']

In [118]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=10, stratify=y)

In [119]:
x_train

,gender,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
52106,0,63.0,0,1,33.33,6.5,145,0.0,0.0,0.0,0.0,1.0,0.0
168293,0,36.0,0,0,24.63,6.2,159,1.0,0.0,0.0,0.0,0.0,0.0
17365,0,52.0,0,0,27.69,6.1,100,1.0,0.0,0.0,0.0,0.0,0.0
4957,0,57.0,0,0,34.40,5.0,158,0.0,0.0,0.0,0.0,0.0,1.0
139523,0,54.0,0,0,28.77,9.0,145,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67251,1,27.0,0,0,27.32,4.5,80,1.0,0.0,0.0,0.0,0.0,0.0
70661,1,18.0,0,0,27.32,6.1,90,1.0,0.0,0.0,0.0,0.0,0.0
5352,0,40.0,0,0,27.32,4.0,158,0.0,0.0,0.0,0.0,1.0,0.0
18268,0,47.0,0,0,25.47,6.2,100,0.0,0.0,0.0,0.0,1.0,0.0
43870,0,20.0,0,0,32.65,5.0,85,1.0,0.0,0.0,0.0,0.0,0.0

In [120]:
x_train = standard_scaler.fit_transform(x_train)
x_test = standard_scaler.transform(x_test)

In [121]:
import pickle

with open('scaler.pkl', 'wb') as f:
    pickle.dump(standard_scaler,f)
with open('gender_encoder.pkl', 'wb') as f:
    pickle.dump(label_gender,f)
with open('smoking_encoder.pkl', 'wb') as f:
    pickle.dump(ohe_smoking,f)

In [122]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [123]:
x_train.shape

(146400, 13)

In [124]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

model.summary()

c:\Users\trilo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [125]:
model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [126]:
##setting the tensorboard
import datetime
log_dir = 'logs/fit/' + datetime.datetime.now().strftime('%Y-%m-%d')
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [127]:
# early stopping

early_stopping_callback = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [128]:
#model training

history = model.fit(
                    x_train,y_train,validation_split=0.2,
                    epochs=10,
                    callbacks=[tensorflow_callback, early_stopping_callback]
                    )

Epoch 1/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8811 - loss: 0.2665 - val_accuracy: 0.8923 - val_loss: 0.2230
Epoch 2/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 977us/step - accuracy: 0.9034 - loss: 0.2011 - val_accuracy: 0.9057 - val_loss: 0.1902
Epoch 3/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 983us/step - accuracy: 0.9088 - loss: 0.1847 - val_accuracy: 0.9083 - val_loss: 0.1852
Epoch 4/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 973us/step - accuracy: 0.9114 - loss: 0.1801 - val_accuracy: 0.9075 - val_loss: 0.1845
Epoch 5/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 962us/step - accuracy: 0.9115 - loss: 0.1783 - val_accuracy: 0.9083 - val_loss: 0.1868
Epoch 6/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 975us/step - accuracy: 0.9128 - loss: 0.1773 - val_accuracy: 0.9104 - val_loss: 0.1822
Epoch 7/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 960us/step - accuracy: 0.9139 - loss: 0.1754 - val_accuracy: 0.9083 - val_loss: 0.1830
Epoch 8/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 961us/step - accuracy: 0.9148 - loss: 0.1753 - val_accuracy: 0.9108 - val_loss: 0.1808
Epoch 9/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 974us/step - accuracy: 0.9155 - loss: 0.1724 - val_accuracy: 0.9105 - val_loss: 0.1796
Epoch 10/10
3660/3660 ━━━━━━━━━━━━━━━━━━━━ 4s 959us/step - accuracy: 0.9156 - loss: 0.1711 - val_accuracy: 0.9103 - val_loss: 0.1798

In [129]:
model.evaluate(x_test,y_test)

1144/1144 ━━━━━━━━━━━━━━━━━━━━ 1s 523us/step - accuracy: 0.9089 - loss: 0.1821

[0.17999491095542908, 0.911448061466217]

In [140]:
y_pred = model.predict(x_test)
y_pred

1144/1144 ━━━━━━━━━━━━━━━━━━━━ 1s 506us/step

array([[6.5195441e-01],
       [1.0000000e+00],
       [1.0000000e+00],
       ...,
       [5.4690819e-02],
       [6.6938692e-01],
       [3.2246973e-08]], dtype=float32)

In [151]:
y_final = [1 if i>0.5 else 0 for i in y_pred]
y_final

[1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 ...]

In [130]:
model.save('diabetes_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [131]:
import tensorboard
%load_ext tensorboard

In [132]:
%tensorboard --logdir logs/fit

In [152]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_final))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91     18300
           1       0.91      0.92      0.91     18300

    accuracy                           0.91     36600
   macro avg       0.91      0.91      0.91     36600
weighted avg       0.91      0.91      0.91     36600